welcome_string = ("█   █ ▄▀▀ █   ▄▀▀ ▄▀▀▄ █▄ ▄█ ▄▀▀\n"
                  "█   █ █   █   █   █  █ █▀▄▀█ █  \n"
                  "█   █ █▀▀ █   █   █  █ █ ▀ █ █▀▀\n"
                  "█▄█▄█ █   █   █   █  █ █   █ █  \n"
                  " ▀ ▀   ▀▀  ▀▀  ▀▀  ▀▀  ▀   ▀  ▀▀\n")
airplane_element = ("\n"
                    "    _    _            _                  \n"
                    "   / \  (_)_ __ _ __ | | __ _ _ __   ___ \n"
                    "  / _ \ | | '__| '_ \| |/ _` | '_ \ / _ \ \n"
                    " / ___ \| | |  | |_) | | (_| | | | |  __/\n"
                    "/_/   \_\_|_|  | .__/|_|\__,_|_| |_|\___|\n"
                    "               |_|                       \n"
                    "               ")
# including a helping manual
help_element = ("\n"
                "    In this this System we have 3 main section we can explore and work with:\n"
                "    -----------------------------------\n"
                "    1- Airplanes:\n"
                "        1.1- Create an airplane\n"
                "            1.1.1- Create a small airplane\n"
                "            1.1.2- Create a medium airplane\n"
                "            1.1.3- Create a Large airplane\n"
                "        1.2- Modify and airplane\n"
                "            1.2.1- Modify airplane company name\n"
                "            1.2.2- Modify airplane departure time\n"
                "            1.2.3- Modify airplane arrival time\n"
                "        1.3- Delete and airplane\n"
                "        1.4- Print airplane information\n"
                "    -----------------------------------\n"
                "    2- Passengers:\n"
                "        2.1- Create a passenger\n"
                "        2.2- Modify a passenger\n"
                "            2.2.1- Modify first name\n"
                "            2.2.2- Modify last name\n"
                "        2.3- Delete a passenger\n"
                "        2.4- Print a passenger\n"
                "           2.4.1- print passenger info\n"
                "           2.4.2- print all passenger reservations\n"
                "------------------------------------\n"
                "    3- Reservations:\n"
                "        3.1- Create a reservation ( pick a plane and a seat )\n"
                "        3.2- Modify a reservation ( modify plane or seat )\n"
                "           3.2.1- Modify airplane reservation\n"
                "           3.2.2- Modify seat on airplane\n"
                "           3.2.3- Modify reservation's passenger\n"
                "        3.3- Cancel a reservation\n"
                "        3.4- Print  a reservation\n")

passenger_element = ("\n"
                     " ____                                          \n"
                     "|  _ \ __ _ ___ ___  ___ _ __   __ _  ___ _ __ \n"
                     "| |_) / _` / __/ __|/ _ \ '_ \ / _` |/ _ \ '__|\n"
                     "|  __/ (_| \__ \__ \  __/ | | | (_| |  __/ |   \n"
                     "|_|   \__,_|___/___/\___|_| |_|\__, |\___|_|   \n"
                     "                               |___/           \n")

menu_element = ("\n"
                " __  __       _         __  __                  \n"
                "|  \/  | __ _(_)_ __   |  \/  | ___ _ __  _   _ \n"
                "| |\/| |/ _` | | '_ \  | |\/| |/ _ \ '_ \| | | |\n"
                "| |  | | (_| | | | | | | |  | |  __/ | | | |_| |\n"
                "|_|  |_|\__,_|_|_| |_| |_|  |_|\___|_| |_|\__,_|\n")

reservation_element = ("\n"
                       " ____                                     _   _                 \n"
                       "|  _ \ ___  ___  ___ _ ____   ____ _ _ __| |_(_) ___  _ __  ___ \n"
                       "| |_) / _ \/ __|/ _ \ '__\ \ / / _` | '__| __| |/ _ \| '_ \/ __|\n"
                       "|  _ <  __/\__ \  __/ |   \ V / (_| | |  | |_| | (_) | | | \__ \ \n"
                       "|_| \_\___||___/\___|_|    \_/ \__,_|_|   \__|_|\___/|_| |_|___/\n")

help_element_header = ("\n"
                       " _   _      _       \n"
                       "| | | | ___| |_ __  \n"
                       "| |_| |/ _ \ | '_ \ \n"
                       "|  _  |  __/ | |_) |\n"
                       "|_| |_|\___|_| .__/ \n"
                       "             |_|    \n")
